config/routes.rb
EngineCrm::Engine.routes.draw do
  resources :lists do
  	post 'add'
  	delete 'remove'
  end


  resources :calendar, only: [:show]

  resources :companies do
    resources :communications
  end
  resources :people, path: 'contacts'
  resources :communications
  root to: 'activities#index'
end

app/models/engine_crm/activity.rb
module EngineCrm
  class Activity < ActiveRecord::Base
    serialize :user_id
    serialize :trackable_id

    attr_accessible :user, :trackable

    def user
      self.user_type.find(self.user_id) rescue nil
    end

    def user=(usr)
      self.user_id = usr.id rescue nil
      self.user_type = usr.class.to_s
    end

    def user_type
      super.constantize
    end

    def trackable
      self.trackable_type.find(self.trackable_id) rescue nil
    end

    def trackable=(obj)
      self.trackable_id = obj.id rescue nil
      self.trackable_type = obj.class.to_s
    end

    def trackable_type
      super.constantize
    end
  end
end

app/models/engine_crm/communication.rb
module EngineCrm
  class Communication < ActiveRecord::Base
    belongs_to :person, class_name: 'EngineCrm::Person'
    belongs_to :company, class_name: 'EngineCrm::Company'

    serialize :user_id

    attr_accessible :details, :company_id, :person, :person_id, :user, :enable_reminder, :reminder_text, :reminder_timestamp, :timestamp

    attr_reader :reminder_text, :enable_reminder
    attr_writer :reminder_text, :enable_reminder

    after_save :create_reminder

    def self.ransackable_attributes(auth_object=nil)
      (column_names - ['id', 'contact_id', 'contact_type', 'updated_at', 'type']) + _ransackers.keys
    end

    def user
      self.user_type.find(self.user_id) rescue nil
    end

    def user=(usr)
      self.user_id = usr.id rescue nil
      self.user_type = usr.class.to_s
    end

    def user_type
      self['user_type'].constantize
    end

    def user_type=(str)
      self['user_type'] = str.to_s
    end

    private
    def create_reminder
      if self.user and self.enable_reminder and ![0, '0'].include? self.enable_reminder
        event = EngineCrm::Event.new
        event.start = self.reminder_timestamp
        event.end = event.start + 1.hour
        event.description = self.reminder_text
        event.user_id = self.user_id
        event.user_type = self.user_type.to_s
        event.save
      end
    end
  end
end

app/models/engine_crm/company.rb
module EngineCrm
  class Company < EngineCrm::Contact
    has_many :communications, class_name: 'EngineCrm::Communication', dependent: :destroy, order: 'timestamp DESC'

    CUSTOM_ATTRS=['website']

    CUSTOM_ATTRS.each do |attr|
      attr_accessible attr.to_sym

      self.class_eval "
        def #{attr}
          self.custom['#{attr}']
        end

        def #{attr}=(a)
          self.custom['#{attr}']=a
        end
      "
    end
  end
end

app/models/engine_crm/contact.rb
require 'activerecord-postgres-hstore'
require 'ransack'

module EngineCrm
  class Contact < ActiveRecord::Base
    serialize :custom, ActiveRecord::Coders::Hstore
    attr_accessible :name, :notes, :phone, :city, :state, :zip, :custom, :contact, :contact_id, :contact_type, :address
    validates_presence_of :name

    has_many :contacts, as: :contact
    belongs_to :contact

    has_and_belongs_to_many :lists, join_table: 'engine_crm_contacts_engine_crm_lists', foreign_key: 'contact_id', class_name: 'EngineCrm::List'

    before_save :sanitize_phone

    def self.ransackable_attributes(auth_object=nil)
      (column_names - ['id', 'contact_id', 'contact_type', 'created_at', 'updated_at', 'type', 'custom']) + _ransackers.keys
    end

    protected
    def sanitize_phone
      self.phone = self.phone.scan(/\d/).join
    end
  end
end

app/models/engine_crm/event.rb
module EngineCrm
  class Event < ActiveRecord::Base
    serialize :user_id
    attr_accessible :description, :end, :start, :title, :user

    def user
      self.user_type.find(self.user_id) rescue nil
    end

    def user=(usr)
      self.user_id = usr.id rescue nil
      self.user_type = usr.class.to_s
    end

    def user_type
      super.constantize
    end
  end
end

app/models/engine_crm/list.rb
module EngineCrm
  class List < ActiveRecord::Base
    attr_accessible :name
		default_scope order('name DESC')

		has_and_belongs_to_many :contacts, join_table: 'engine_crm_contacts_engine_crm_lists', foreign_key: 'list_id'
  end
end

app/models/engine_crm/person.rb
module EngineCrm
  class Person < EngineCrm::Contact
    has_many :communications, class_name: 'EngineCrm::Communication'

    validates_format_of :email, with: /@/, allow_nil: true, allow_blank: true

    CUSTOM_ATTRS=['title', 'email', 'cell_phone']

    CUSTOM_ATTRS.each do |attr|
      attr_accessible attr.to_sym

      self.class_eval "
        def #{attr}
          self.custom['#{attr}']
        end

        def #{attr}=(a)
          self.custom['#{attr}']=a
        end
      "
    end
  end
end

app/controllers/engine_crm/activities_controller.rb
require_dependency 'engine_crm/application_controller'

module EngineCrm
  class ActivitiesController < ApplicationController
    def index
      @activities = Activity.order('created_at desc').limit(20)
    end
  end
end

app/controllers/engine_crm/application_controller.rb
module EngineCrm
  class ApplicationController < ::ApplicationController
    before_filter :set_user

    protected
    def track_activity(trackable)
      a = Activity.new
      a.action = params[:action]
      a.user = @user
      a.trackable = trackable
      a.save
    end

    def set_user
      @user = send(EngineCrm.current_user_method) if EngineCrm.current_user_method
    end
  end
end

app/controllers/engine_crm/calendar_controller.rb
require_dependency 'engine_crm/application_controller'
require 'icalendar'
require 'date'

module EngineCrm
  class CalendarController < ApplicationController
    include Icalendar
    respond_to :ics
    def show
      cal = Calendar.new

      @events = EngineCrm::Event.where(user_id: params[:id]).all

      @events.each do |event|
        cal.event do
          dtstart event.start
          dtend event.end
          summary event.title
          description event.description
        end
      end

      render text: cal.to_ical
    end
  end
end

app/controllers/engine_crm/communications_controller.rb
require_dependency 'engine_crm/application_controller'

module EngineCrm
  class CommunicationsController < ApplicationController
    before_filter :set_communication, only: [:show, :edit, :update, :destroy]
    before_filter :set_company

    # GET /communications
    def index
      @search = scope_communications.search(params[:q])
      @communications = @search.result
      @search.build_condition if @search.conditions.empty?
      @search.build_sort if @search.sorts.empty?
    end

    # GET /communications/1
    def show
    end

    # GET /communications/new
    def new
      @communication = EngineCrm::Communication.new
      @communication.reminder_text = "Call #{EngineCrm::Company.select('name').find(params[:company_id]).name}" if params[:company_id]
      @communication.company ||= EngineCrm::Company.find(params[:company_id]) if params[:company_id]
    end

    # GET /communications/1/edit
    def edit
    end

    # POST /communications
    def create
      @communication = EngineCrm::Communication.new(communication_params)
      if @user
        @communication.user = @user
      end

      if @communication.save
        track_activity @communication
        redirect_to :back, notice: 'Communication was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /communications/1
    def update
      if @communication.update_attributes(communication_params)
        track_activity @communication
        redirect_to :back, notice: 'Communication was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /communications/1
    def destroy
      @communication.destroy
      track_activity @communication
      redirect_to :back, notice: 'Communication was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_communication
        @communication = EngineCrm::Communication.find(params[:id])
      end

    def scope_communications
      if @company
        @company.communications
      else
        EngineCrm::Communication
      end
    end

    def set_company
      @company = EngineCrm::Company.find(params[:company_id]) if params[:company_id]
    end

      # Only allow a trusted parameter "white list" through.
      def communication_params
        params[:communication].reject do |key, val|
          key == :user_id
        end
      end

    def reminder_params
      params[:reminder]
    end
  end
end

app/controllers/engine_crm/companies_controller.rb
require_dependency 'engine_crm/application_controller'

module EngineCrm
  class CompaniesController < ApplicationController
    before_filter :set_company, only: [:show, :edit, :update, :destroy]

    # GET /companies
    def index
      @search = EngineCrm::Company.search(params[:q])
      @companies = @search.result
      @search.build_condition if @search.conditions.empty?
      @search.build_sort if @search.sorts.empty?
    end

    # GET /companies/1
    def show
    end

    # GET /companies/new
    def new
      @company = EngineCrm::Company.new
    end

    # GET /companies/1/edit
    def edit
    end

    # POST /companies
    def create
      @company = EngineCrm::Company.new(company_params)

      if @company.save
        redirect_to @company, notice: 'Company was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /companies/1
    def update
      if @company.update_attributes(company_params)
        redirect_to @company, notice: 'Company was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /companies/1
    def destroy
      @company.destroy
      redirect_to companies_url, notice: 'Company was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_company
        @company = EngineCrm::Company.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def company_params
        params[:company]
      end
  end
end

app/controllers/engine_crm/lists_controller.rb
require_dependency "engine_crm/application_controller"

module EngineCrm
  class ListsController < ApplicationController
  	before_filter :set_list, only: [:show, :edit, :update, :destroy, :add, :remove]
		before_filter :set_contact, only: [:add, :remove]

  	def index
  		@lists = EngineCrm::List.all
    end

    def show
    end

    def edit
    end

    def update
      if @list.update_attributes(list_params)
        redirect_to :back, notice: 'List was successfully updated.'
      else
        render action: 'edit'
      end
    end

    def new
    	@list = EngineCrm::List.new
    end

    def create
    	@list = EngineCrm::List.new(list_params)

      if @list.save
        redirect_to :back, notice: 'List was successfully created.'
      else
        render action: 'new'
      end
    end

    def add
      @list.contacts << @contact
      @list.save
      @contact.save
      redirect_to :back
    end

    def remove
      @contact.list_id = nil
      @contact.save
      redirect_to :back
    end

    def destroy
      @list.destroy
      redirect_to lists_url, notice: 'List was successfully destroyed.'
    end

    private
    def set_list
    	@list = EngineCrm::List.find(params[:list_id] || params[:id])
    end

    def set_contact
    	@contact = EngineCrm::Contact.find(params[:contact_id])
    end

    # Only allow a trusted parameter "white list" through.
    def list_params
      params[:list]
    end
  end
end

app/controllers/engine_crm/people_controller.rb
require_dependency 'engine_crm/application_controller'

module EngineCrm
  class PeopleController < ApplicationController
    before_filter :set_person, only: [:show, :edit, :update, :destroy]

    # GET /people
    def index
      @search = EngineCrm::Person.search(params[:q])
      @people = @search.result
      @search.build_condition if @search.conditions.empty?
      @search.build_sort if @search.sorts.empty?
    end

    # GET /people/1
    def show
    end

    # GET /people/new
    def new
      @person = EngineCrm::Person.new
      @person.contact ||= EngineCrm::Company.find(params[:company_id]) if params[:company_id]
    end

    # GET /people/1/edit
    def edit
    end

    # POST /people
    def create
      @person = EngineCrm::Person.new(person_params)

      if @person.save
        redirect_to :back, notice: 'Person was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /people/1
    def update
      if @person.update_attributes(person_params)
        redirect_to :back, notice: 'Person was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /people/1
    def destroy
      @person.destroy
      redirect_to :back, notice: 'Person was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_person
        @person = EngineCrm::Person.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def person_params
        params[:person]
      end
  end
end

app/helpers/engine_crm/activities_helper.rb
module EngineCrm
  module ActivitiesHelper
  end
end

app/helpers/engine_crm/application_helper.rb
module EngineCrm
  module ApplicationHelper
    def link_to_add_fields(name, f, type)
      new_object = f.object.send "build_#{type}"
      id = "new_#{type}"
      fields = f.send("#{type}_fields", new_object, child_index: id) do |builder|
        render(type.to_s + '_fields', f: builder)
      end
      link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", '')})
    end
  end
end

app/helpers/engine_crm/calendar_helper.rb
module EngineCrm
  module CalendarHelper
  end
end

app/helpers/engine_crm/communications_helper.rb
module EngineCrm
  module CommunicationsHelper
  end
end

app/helpers/engine_crm/companies_helper.rb
module EngineCrm
  module CompaniesHelper
  end
end

app/helpers/engine_crm/lists_helper.rb
module EngineCrm
  module ListsHelper
  end
end

app/views/engine_crm/companies/_condition_fields.html.erb
<div class="field">
  <%= f.attribute_fields do |a| %>
      <%= a.attribute_select associations: [:communications, :contacts] %>
  <% end %>
  <%= f.predicate_select %>
  <%= f.value_fields do |v| %>
      <%= v.text_field :value %>
  <% end %>
  <%= link_to 'remove', '#', class: 'remove_fields' %>
</div>

app/views/engine_crm/companies/_form.html.erb
<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table>
      <tbody>
      <tr class="field">
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :phone %></td>
        <td><%= f.text_field :phone %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :website %></td>
        <td><%= f.text_field :website %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :notes %></td>
        <td><%= f.text_area :notes %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :address %></td>
        <td><%= f.text_field :address %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :city %></td>
        <td><%= f.text_field :city %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :state %></td>
        <td><%= f.text_field :state %></td>
      </tr>
      <tr class="field">
        <td><%= f.label :zip %></td>
        <td><%= f.text_field :zip %></td>
      </tr>
      </tbody>
    </table>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/engine_crm/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', :back %>

app/views/engine_crm/companies/index.html.erb
<div class="span9">
  <h1>Companies</h1>

  <%= link_to 'New Company', new_company_path %>
  <table>
    <thead>
      <tr>
        <th><%= sort_link @search, :name, 'Company Name' %></th>
        <th><%= sort_link @search, :address, 'Address' %></th>
        <th><%= sort_link @search, :city, 'City' %></th>
        <th><%= sort_link @search, :state, 'State' %></th>
        <th><%= sort_link @search, :phone, 'Phone' %></th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td><%= link_to company.name, company %></td>
          <td><%= simple_format(company.address) %></td>
          <td><%= company.city %></td>
          <td><%= company.state %></td>
          <td><%= company.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render 'engine_crm/shared/search' %>

app/views/engine_crm/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/engine_crm/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @company.name %></h1>

<div class="span6">
  <table>
    <tbody>
    <tr>
      <td>Notes:</td>
      <td><%= @company.notes %></td>
    </tr>
    <tr>
      <td>Phone:</td>
      <td><%= @company.phone %></td>
    </tr>
    <tr>
      <td>Website:</td>
      <td><%= @company.website %></td>
    </tr>
    <tr>
      <td>Address:</td>
      <td><%= @company.address %></td>
    </tr>
    <tr>
      <td>City:</td>
      <td><%= @company.city %></td>
    </tr>
    <tr>
      <td>State:</td>
      <td><%= @company.state %></td>
    </tr>
    <tr>
      <td>Zip:</td>
      <td><%= @company.zip %></td>
    </tr>
    <% @company.custom.reject { |c| EngineCrm::Company::CUSTOM_ATTRS.include? c }.each do |key, value| %>
        <tr>
          <td><%= key %></td>
          <td><%= value %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <h3>Contacts</h3>
  <%= link_to 'New Contact', new_person_path(company_id: @company.id) %>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @company.contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.name, person_path(contact) %></td>
          <td><%= number_to_phone contact.phone %></td>
          <td><%= mail_to contact.email, contact.email %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div class="span6">
  <h3>Communications</h3>
  <%= link_to 'New Communication', new_company_communication_path(@company) %>
  <table>
    <tbody>
        <% @company.communications.each do |comm| %>
            <tr>
              <td><%= comm.timestamp %></td>
              <td><%= comm.person.name %></td>
              <td><%= comm.details %></td>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', :back %>